In [2]:
import numpy as np

<h1>The Basics</h1>

In [28]:
a = np.array([1,2,3],dtype="int8")
print(a)

[1 2 3]


In [39]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]], dtype="float16")
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [11]:
#get Dimension
a.ndim

1

In [12]:
#get Shape
b.shape

(2, 3)

In [37]:
# Get Type
a.dtype
b.dtype

dtype('float64')

In [32]:
#Get size of an element, no of bytes consumed by a element
a.itemsize
b.itemsize

1

In [29]:
#Get total size of the array
a.nbytes

3

<h1>Accessing/Changing specific elements, rows, columns, etc</h1>

In [57]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [58]:
a.shape

(2, 7)

In [59]:
#get a specific element at [r, c]c
#gives a wrapper as output
a[1, 5]

np.int64(13)

In [60]:
# if want direct value as output
a[1, 5].item()

13

In [66]:
# Get a specific row
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [65]:
#GEt a specific column
a[:,4]

array([ 5, 12])

In [64]:
#Getting in step manner [startindex:endindex:stepsize]
a[0, 1:4:2]

array([2, 4])

In [67]:
#reverse a sepcific row
a[0, ::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [69]:
#reverse a specific column
a[::-1,4]

array([12,  5])

In [71]:
#change a element
a[1,3]=34
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 34, 12, 13, 14]])

In [73]:
#change a column
a[:,4]=[36,64]
a

array([[ 1,  2,  3,  4, 36,  6,  7],
       [ 8,  9, 10, 34, 64, 13, 14]])

In [77]:
#3D example
b = np.array([[[1,2],[3,4],[3,4]],[[5,6],[5,6],[7,8]]])
print(b)
print(arr.T)
print(arr.flat)
for i in arr.flat:
    print(i)

[[[1 2]
  [3 4]
  [3 4]]

 [[5 6]
  [5 6]
  [7 8]]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
1
2
3
4
5
6
7
8


In [75]:
#Get a specific element 
b[1,0,0]

np.int64(5)

In [81]:
b.shape

(2, 3, 2)

In [83]:
b[:,:,0] #shape help to find how many elements and in which manner i will get after slicing like b[1,:,0] will give 3 elements array as shape is 3 at 2 level


array([[1, 3, 3],
       [5, 5, 7]])

In [85]:
#shape will also help in replace
b[:,0,:]= [[11,22],[33,44]]
b

array([[[11, 22],
        [ 3,  4],
        [ 3,  4]],

       [[33, 44],
        [ 5,  6],
        [ 7,  8]]])

In [72]:
np.linspace(1,7,6)

array([1. , 2.2, 3.4, 4.6, 5.8, 7. ])

In [74]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [88]:
#All 0s matrix
np.zeros((3,6),dtype="int8")

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int8)

In [91]:
#All 1s matrix
np.ones((3,6,3), dtype="int8")

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int8)

In [93]:
#Any other number
np.full((4,3,2), 8, dtype="int8")

array([[[8, 8],
        [8, 8],
        [8, 8]],

       [[8, 8],
        [8, 8],
        [8, 8]],

       [[8, 8],
        [8, 8],
        [8, 8]],

       [[8, 8],
        [8, 8],
        [8, 8]]], dtype=int8)

In [94]:
#make array of any number like the structure of any other array ( using full)
np.full(b.shape, 9, dtype="int8")

array([[[9, 9],
        [9, 9],
        [9, 9]],

       [[9, 9],
        [9, 9],
        [9, 9]]], dtype=int8)

In [107]:
#Random decimal numbers
np.random.rand(5,3,6).astype(np.float64)
#also can use other array shape for this

array([[[0.54789514, 0.3176137 , 0.39038832, 0.6681817 , 0.30037506,
         0.96013756],
        [0.72507011, 0.99430689, 0.52389866, 0.51761852, 0.31181099,
         0.91174458],
        [0.57763731, 0.73749021, 0.57312756, 0.51846286, 0.96907848,
         0.70603836]],

       [[0.10122468, 0.88634965, 0.49208658, 0.75334738, 0.04966458,
         0.9890421 ],
        [0.93598007, 0.96465125, 0.02338013, 0.50812804, 0.0513929 ,
         0.32384924],
        [0.16385659, 0.93653701, 0.04928865, 0.66193445, 0.74087372,
         0.35658265]],

       [[0.10686338, 0.77098408, 0.2199223 , 0.30209295, 0.15219758,
         0.22514339],
        [0.0285622 , 0.688087  , 0.85635188, 0.68074357, 0.87383881,
         0.03526291],
        [0.07564336, 0.64297642, 0.48510581, 0.25835425, 0.58973579,
         0.89227983]],

       [[0.49939319, 0.72294187, 0.10664135, 0.311788  , 0.25368197,
         0.09129042],
        [0.45748391, 0.09070172, 0.15556095, 0.17467839, 0.38369748,
         0.1852

In [114]:
# creates 5 random numbers from a uniform distribution between 0 and 1
np.random.uniform(0,1, size = (3,4)).astype(np.float32)

array([[0.78130245, 0.12662227, 0.9556252 , 0.5049425 ],
       [0.04322064, 0.19786824, 0.24719617, 0.22644532],
       [0.01537819, 0.19936414, 0.954489  , 0.13708511]], dtype=float32)

In [110]:
#make array of any number like the structure of any other array ( using full_like)
np.full_like(b, 9, dtype="int8")

array([[[9, 9],
        [9, 9],
        [9, 9]],

       [[9, 9],
        [9, 9],
        [9, 9]]], dtype=int8)

In [112]:
#Random Integer Values
np.random.randint(3,8,size=(5,4,6),dtype= "int8")

array([[[3, 7, 7, 5, 4, 7],
        [7, 7, 6, 7, 5, 7],
        [7, 5, 6, 5, 4, 6],
        [4, 5, 7, 7, 4, 4]],

       [[5, 6, 3, 6, 4, 4],
        [6, 7, 4, 7, 6, 3],
        [3, 6, 5, 7, 6, 4],
        [4, 4, 6, 5, 6, 7]],

       [[5, 5, 6, 3, 3, 3],
        [4, 4, 6, 4, 7, 5],
        [4, 7, 4, 4, 5, 4],
        [6, 5, 6, 7, 4, 7]],

       [[3, 3, 5, 7, 4, 6],
        [6, 4, 4, 5, 5, 4],
        [3, 5, 5, 4, 6, 6],
        [3, 7, 3, 5, 6, 3]],

       [[7, 7, 3, 6, 7, 7],
        [7, 3, 3, 3, 7, 7],
        [3, 3, 3, 5, 7, 4],
        [7, 3, 3, 7, 4, 4]]], dtype=int8)

In [116]:
#make a identity matrix 
np.identity(7, dtype = "int8")

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [35]:
#Repeat an array
arr = np.array([[[1,2,3]]])
r1 = np.repeat(arr,6, axis=2)
r1

array([[[1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3]]])

In [134]:
#make matrix of your choice by some pattern

matrix = np.ones((7,7))
print(matrix)
zeros = np.zeros((5,5))
zeros[2,2]=11
print(zeros)
matrix[1:-1,1:-1]= zeros
print(matrix)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0. 11.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0. 11.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.]]


In [135]:
#Be careful when copying arrays
a = np.array([1,2,3])
b = a.copy()
b[0] = 110
a


array([1, 2, 3])

<h1>Mathematics</h1>

In [136]:
a= np.array([1,2,4,6,67,8,8])


In [137]:
a+2

array([ 3,  4,  6,  8, 69, 10, 10])

In [138]:
a-2

array([-1,  0,  2,  4, 65,  6,  6])

In [139]:
a+=4
a

array([ 5,  6,  8, 10, 71, 12, 12])

In [140]:
a*5

array([ 25,  30,  40,  50, 355,  60,  60])

In [141]:
a/3

array([ 1.66666667,  2.        ,  2.66666667,  3.33333333, 23.66666667,
        4.        ,  4.        ])

In [143]:
b = np.array([2,4,6,2,5,2,4])
a+b

array([ 7, 10, 14, 12, 76, 14, 16])

In [144]:
a**3

array([   125,    216,    512,   1000, 357911,   1728,   1728])

In [145]:
#take the sin 
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.98935825, -0.54402111,  0.95105465,
       -0.53657292, -0.53657292])

<h1>Linear Algebra</h1>

In [6]:
a = np.ones((4,7))
print(a)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [5]:
b = np.full((7,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]
 [2 2]]


In [7]:
np.matmul(a,b)

array([[14., 14.],
       [14., 14.],
       [14., 14.],
       [14., 14.]])

In [11]:
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

# Statistics

In [33]:
stats = np.array([[[1,2],[10,9]],[[4,5],[11,6]],[[7,8],[12,6]]])
np.min(stats, axis=0)

array([[ 1,  2],
       [10,  6]])

In [36]:
np.max(stats)

np.int64(12)

In [101]:
print(stats.argmax(axis = ))
print(stats.argmin())

[[2 2]
 [2 2]]
0


# Reorganizing Arrays 

In [43]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
after = arr.reshape((4,2))
after

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [50]:
#vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
a = np.vstack([v1,v2,v2,v1])


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [53]:
#horizontal stack
a = np.full((3,4),2)
b = np.full((3,7),5)
np.hstack([a,b])

array([[2, 2, 2, 2, 5, 5, 5, 5, 5, 5, 5],
       [2, 2, 2, 2, 5, 5, 5, 5, 5, 5, 5],
       [2, 2, 2, 2, 5, 5, 5, 5, 5, 5, 5]])

# Miscellaneous


In [59]:
file_text = np.genfromtxt('data.txt', delimiter= ',')
file_text=file_text.astype("int32")
file_text

array([[ 1,  2,  3, 45,  6,  8,  9, 90],
       [ 5,  7,  8,  3,  5,  7,  3,  8],
       [ 7,  3,  7,  9,  9,  4,  4,  7]], dtype=int32)

#Boolean Masking and Advanced Indexing

In [61]:
file_text>=4

array([[False, False, False,  True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True,  True, False,  True],
       [ True, False,  True,  True,  True,  True,  True,  True]])

In [64]:
np.any(file_text>4, axis = 0)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [65]:
np.all(file_text>4, axis = 0)

array([False, False, False, False,  True, False, False,  True])

In [69]:
file_text[2,[1,6,7]]

array([3, 4, 7], dtype=int32)

In [70]:
(~((file_text > 4) & (file_text < 8)))

array([[ True,  True,  True,  True, False,  True,  True,  True],
       [False, False,  True,  True, False, False,  True,  True],
       [False,  True, False,  True,  True,  True,  True, False]])